export const ShopActionTyeps = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTION_FAILURE',
};
