const SHOP_DATA = [
  {
    id: 1,
    title: 'BEDROOM',
    routeName: 'bedroom',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: '../assets/bathroom/bath_pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: '../assets/bathroom/ faux_succulent_plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: '../assets/bathroom/bamboo_tray.jpeg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: '../assets/bathroom/bath_disco_light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: '../assets/bathroom/tech_shower_curtain.jpeg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: '../assets/bathroom/led_candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: '../assets/bathroom/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: '/assets/bathroom/shower_speaker.jpeg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: '/assets/bathroom/tissue_mag_holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: '/assets/bathroom/led_toilet.jpeg',
        price: 9.99,
      },
    ],
  },
  {
    id: 2,
    title: 'BATHROOM',
    routeName: 'bathroom',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: '../assets/bathroom/bath_pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: '../assets/bathroom/ faux_succulent_plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: '../assets/bathroom/bamboo_tray.jpeg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: '../assets/bathroom/bath_disco_light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: '../assets/bathroom/tech_shower_curtain.jpeg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: '../assets/bathroom/led_candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: '../assets/bathroom/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: '/assets/bathroom/shower_speaker.jpeg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: '/assets/bathroom/tissue_mag_holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: '/assets/bathroom/led_toilet.jpeg',
        price: 9.99,
      },
    ],
  },
  {
    id: 3,
    title: 'KITCHEN',
    routeName: 'kitchen',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: '../assets/bathroom/bath_pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: '../assets/bathroom/ faux_succulent_plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: '../assets/bathroom/bamboo_tray.jpeg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: '../assets/bathroom/bath_disco_light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: '../assets/bathroom/tech_shower_curtain.jpeg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: '../assets/bathroom/led_candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: '../assets/bathroom/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: '/assets/bathroom/shower_speaker.jpeg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: '/assets/bathroom/tissue_mag_holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: '/assets/bathroom/led_toilet.jpeg',
        price: 9.99,
      },
    ],
  },
  {
    id: 4,
    title: 'OUTDOOR & MORE',
    routeName: 'outdoor&more',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: '../assets/bathroom/bath_pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: '../assets/bathroom/ faux_succulent_plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: '../assets/bathroom/bamboo_tray.jpeg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: '../assets/bathroom/bath_disco_light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: '../assets/bathroom/tech_shower_curtain.jpeg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: '../assets/bathroom/led_candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: '../assets/bathroom/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: '/assets/bathroom/shower_speaker.jpeg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: '/assets/bathroom/tissue_mag_holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: '/assets/bathroom/led_toilet.jpeg',
        price: 9.99,
      },
    ],
  },
  {
    id: 5,
    title: 'LIVING ROOM',
    routeName: 'livingroom',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: '../assets/bathroom/bath_pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: '../assets/bathroom/ faux_succulent_plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: '../assets/bathroom/bamboo_tray.jpeg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: '../assets/bathroom/bath_disco_light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: '../assets/bathroom/tech_shower_curtain.jpeg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: '../assets/bathroom/led_candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: '../assets/bathroom/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: '/assets/bathroom/shower_speaker.jpeg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: '/assets/bathroom/tissue_mag_holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: '/assets/bathroom/led_toilet.jpeg',
        price: 9.99,
      },
    ],
  },
];
