const STORE_DATA = [
  {
    id: 1,
    title: 'BEDROOM',
    routeName: 'bedroom',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: 'https://i.ibb.co/72qXGyd/bath-pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: 'https://i.ibb.co/MZGTXnX/faux-succulent-plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: 'https://i.ibb.co/tL0NKBw/bamboo-tray.jpg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: 'https://i.ibb.co/5cPntjC/bath-disco-light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: 'https://i.ibb.co/5k3vBHC/tech-shower-curtain.jpg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: 'https://i.ibb.co/LryP4wD/led-candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: 'https://i.ibb.co/jw4X1Qv/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: 'https://i.ibb.co/fdH7mGx/shower-speaker.jpg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: 'https://i.ibb.co/ZBrKTfr/tissue-mag-holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: 'https://i.ibb.co/LC91CjX/led-toilet.jpg',
        price: 9.99,
      },
    ],
  },
  {
    id: 2,
    title: 'BATHROOM',
    routeName: 'bathroom',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: 'https://i.ibb.co/72qXGyd/bath-pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: 'https://i.ibb.co/MZGTXnX/faux-succulent-plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: 'https://i.ibb.co/tL0NKBw/bamboo-tray.jpg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: 'https://i.ibb.co/5cPntjC/bath-disco-light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: 'https://i.ibb.co/5k3vBHC/tech-shower-curtain.jpg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: 'https://i.ibb.co/LryP4wD/led-candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: 'https://i.ibb.co/jw4X1Qv/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: 'https://i.ibb.co/fdH7mGx/shower-speaker.jpg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: 'https://i.ibb.co/ZBrKTfr/tissue-mag-holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: 'https://i.ibb.co/LC91CjX/led-toilet.jpg',
        price: 9.99,
      },
    ],
  },
  {
    id: 3,
    title: 'KITCHEN',
    routeName: 'kitchen',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: 'https://i.ibb.co/72qXGyd/bath-pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: 'https://i.ibb.co/MZGTXnX/faux-succulent-plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: 'https://i.ibb.co/tL0NKBw/bamboo-tray.jpg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: 'https://i.ibb.co/5cPntjC/bath-disco-light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: 'https://i.ibb.co/5k3vBHC/tech-shower-curtain.jpg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: 'https://i.ibb.co/LryP4wD/led-candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: 'https://i.ibb.co/jw4X1Qv/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: 'https://i.ibb.co/fdH7mGx/shower-speaker.jpg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: 'https://i.ibb.co/ZBrKTfr/tissue-mag-holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: 'https://i.ibb.co/LC91CjX/led-toilet.jpg',
        price: 9.99,
      },
    ],
  },
  {
    id: 4,
    title: 'OUTDOOR & MORE',
    routeName: 'outdoor&more',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: 'https://i.ibb.co/72qXGyd/bath-pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: 'https://i.ibb.co/MZGTXnX/faux-succulent-plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: 'https://i.ibb.co/tL0NKBw/bamboo-tray.jpg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: 'https://i.ibb.co/5cPntjC/bath-disco-light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: 'https://i.ibb.co/5k3vBHC/tech-shower-curtain.jpg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: 'https://i.ibb.co/LryP4wD/led-candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: 'https://i.ibb.co/jw4X1Qv/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: 'https://i.ibb.co/fdH7mGx/shower-speaker.jpg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: 'https://i.ibb.co/ZBrKTfr/tissue-mag-holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: 'https://i.ibb.co/LC91CjX/led-toilet.jpg',
        price: 9.99,
      },
    ],
  },
  {
    id: 5,
    title: 'LIVING ROOM',
    routeName: 'livingroom',
    items: [
      {
        id: 1,
        name: 'Bath Pillow',
        imageUrl: 'https://i.ibb.co/72qXGyd/bath-pillow.png',
        price: 22.24,
      },
      {
        id: 2,
        name: 'Faux Succulent Plant',
        imageUrl: 'https://i.ibb.co/MZGTXnX/faux-succulent-plant.png',
        price: 7.99,
      },
      {
        id: 3,
        name: 'Bamboo Bathtub Tray',
        imageUrl: 'https://i.ibb.co/tL0NKBw/bamboo-tray.jpg',
        price: 31.99,
      },
      {
        id: 4,
        name: 'Baththub Disco Lights',
        imageUrl: 'https://i.ibb.co/5cPntjC/bath-disco-light.png',
        price: 12,
      },
      {
        id: 5,
        name: 'Tech Shower Curtain',
        imageUrl: 'https://i.ibb.co/5k3vBHC/tech-shower-curtain.jpg',
        price: 14.2,
      },
      {
        id: 6,
        name: 'Flamless Led Candles',
        imageUrl: 'https://i.ibb.co/LryP4wD/led-candles.png',
        price: 17,
      },
      {
        id: 7,
        name: 'Colorful Bath Bomb set ',
        imageUrl: 'https://i.ibb.co/jw4X1Qv/bathbombs.png',
        price: 21,
      },
      {
        id: 8,
        name: 'Waterproof Shower Speaker',
        imageUrl: 'https://i.ibb.co/fdH7mGx/shower-speaker.jpg',
        price: 40.99,
      },
      {
        id: 9,
        name: 'Tissue and Magazine Holder',
        imageUrl: 'https://i.ibb.co/ZBrKTfr/tissue-mag-holder.png',
        price: 19.99,
      },
      {
        id: 10,
        name: 'LED Toilet Lights',
        imageUrl: 'https://i.ibb.co/LC91CjX/led-toilet.jpg',
        price: 9.99,
      },
    ],
  },
];

export default STORE_DATA;
